---
title: "Visualization 2"
author: "Esther Kyeremah"
date: "2023-10-23"
output: github_document
---

```{r}
library(tidyverse)
library(ggridges)
```

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USW00022534", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2021-01-01",
    date_max = "2022-12-31") |>
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USW00022534 = "Molokai_HI",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) |>
  select(name, id, everything())
```




```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = .5)
  
```


#Labels

```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = .5) +
  labs( 
    title = "Temprerature plot",
    x = "Minimum daily temperature(C)",
    y = "Maximum daily temperature(C)",
    caption = "Data from rnoaa package; temperatures in 2017."
    ) +
  scale_x_continuous(
    breaks = c(-15, 0 , 15),
    labels = c("-15C", "OC", "15C")) + 
  scale_y_continuous(
    trans = "sqrt",
    position = "right"
  )
```

Look at color scales and change the variable key name to LOCATION
```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = .5) +
  labs( 
    title = "Temprerature plot",
    x = "Minimum daily temperature(C)",
    y = "Maximum daily temperature(C)",
    caption = "Data from rnoaa package; temperatures in 2017." ) +
  scale_color_hue(
   name = "Location",
    h = c(100,300))
```


Using viridis
```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = .5) +
  labs( 
    title = "Temprerature plot",
    x = "Minimum daily temperature(C)",
    y = "Maximum daily temperature(C)",
    caption = "Data from rnoaa package; temperatures in 2017." ) +
    viridis::scale_color_viridis(
      name = "Location",
   discrete = TRUE)
```

##Themes 
The theme legend position has to come after youve chosen to use theme_minmal..other theems are theme_classic etc... you can also use ggthemes::(and then pick from he options)
```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = .5) +
  labs( 
    title = "Temprerature plot",
    x = "Minimum daily temperature(C)",
    y = "Maximum daily temperature(C)",
    caption = "Data from rnoaa package; temperatures in 2017." ) +
    viridis::scale_color_viridis(
      name = "Location",
   discrete = TRUE) +
theme_minimal() +
theme(legend.position = "bottom")
```

##Setting options

```{r, eval = FALSE}
library(tidyverse)

knitr:: opts_chunk$set(
  fig.width = 6,
  gif.asp = .6,
  out.width = "90%"
)


theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.comtinuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_color_viridis_d()
scale_fill_discrete = scale_fill_viridis_d()
)
```


